### ISSUE TITLE
MinGW compilation failed

### ISSUE THREAD

**Issue by Kaspek2480** [sondernextdoor/WindowsHardwareInfo#2]
Possible to compile using mingw? I'm getting those three errors during compilation

```
windows_hardware_info.h:312:83: error: the value of 'DiskExtents' is not usable in a constant expression
  312 |                                 offsetof(VOLUME_DISK_EXTENTS, Extents[DiskExtents.NumberOfDiskExtents]),
      |                                                                                   ^~~~~~~~~~~~~~~~~~~
```

```
windows_hardware_info.h:195:33: error: cast from 'BSTR' {aka 'wchar_t*'} to 'unsigned int' loses precision [-fpermissive]
  195 |                 Value.push_back((T) ((bstr_t) Variant.bstrVal).copy());
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

```
error: cast from 'BSTR' {aka 'wchar_t*'} to 'int' loses precision [-fpermissive]
  195 |                 Value.push_back((T) ((bstr_t) Variant.bstrVal).copy());
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by sondernextdoor** [comment]
> windows_hardware_info.h:312:83: error: the value of 'DiskExtents' is not usable in a constant expression
  312 |                                 offsetof(VOLUME_DISK_EXTENTS, Extents[DiskExtents.NumberOfDiskExtents]),
      |                                                                                   ^~~~~~~~~~~~~~~~~~~

This error can be avoided by defining an alternate version of "offsetof" like so: 

`#define _offsetof(s,m) ((::size_t)&reinterpret_cast<char volatile&>((((s*)0)->m)))` 

then swap "offsetof" for "_offsetof".

> windows_hardware_info.h:195:33: error: cast from 'BSTR' {aka 'wchar_t*'} to 'unsigned int' loses precision [-fpermissive]
  195 |                 Value.push_back((T) ((bstr_t) Variant.bstrVal).copy());
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

> error: cast from 'BSTR' {aka 'wchar_t*'} to 'int' loses precision [-fpermissive]
  195 |                 Value.push_back((T) ((bstr_t) Variant.bstrVal).copy());
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Compile with -fpermissive

However, even when avoiding these errors, MinGW still doesn't work nicely with WMI services; it still won't compile due to numerous undefined references. While I'm sure you can get it to work with enough tinkering, it's more effort than it's worth imo.
